### ISSUE TITLE
help with slow down possibly due to `:sentinel` of `flymake-collection-define`

### ISSUE THREAD

**Issue by ed9w2in6** [mohkale/flymake-rest#30]
Despite `flymake-collection-define` uses async process to call linter I still experience slow down (hangs).
Using `explain-pause` I saw that the slow down is caused by the sentinel.

```
... skipped
 ► Slow: 2912 ms
<bytecode> (references: (process-live-p make-closure          1 4080.00  4080     1
  plist-get buffer-local-value flymake-collection-define--procs
  flymake-collection-ruff nil process-buffer match-data
  flymake-collection-parse-json buffer-substring-no-properties t row location
  column end_location code message flymake-diag-region :warning propertize face
  flymake-collection-diag-id integer-or-marker-p apply flymake-make-diagnostic
  flymake--log-1 :error process-exit-status format))
 ► Slow: 4080 ms
<bytecode> (references: (process-live-p make-closure          1  261.00   261     1
  plist-get buffer-local-value flymake-collection-define--procs
  flymake-collection-ruff nil process-buffer match-data
  flymake-collection-parse-json buffer-substring-no-properties t row location
  column end_location code message flymake-diag-region :warning propertize face
  flymake-collection-diag-id integer-or-marker-p apply flymake-make-diagnostic
  flymake--log-1 :error process-exit-status format))
... skipped
```

I believe those are the generated sentinel code, ref:
https://github.com/mohkale/flymake-collection/blob/fec8be1c53e630b45136ab8714184bf85850c64e/src/flymake-collection-define.el#L267-L272

I must admit I have just started trying `flymake` and I may not have the best setup.
I have already set `flymake-no-changes-timeout` to 4.
May I ask if you experience such slow down too?

**Comment by mohkale** [comment]
I've never really experienced any slow down from flymake collections checkers. Could you share a few more details about the issues you're seeing. A sample file, which checker you're running and how many lints you're seeing produced should help point in the right direction.

**Comment by fbergroth** [comment]
I've also experienced slowdowns. It really showed in an old python file where ruff reported hundreds of errors. I could barely make edits using ruff with flymake-collections. If I instead configured `python-flymake-command` to use ruff and used the builtin `python-flymake` checker, everything was quite smooth.

**Comment by mohkale** [comment]
If you could share the python file in question I can try reproducing it. From a cursory look the only impacting difference I can see is python-flymake uses regex parsing whereas we use json. Out of curiosity have you built the MFA with libjanson support so JSON encoding/decoding is quick :thinking:.

**Comment by fbergroth** [comment]
I can't share that particular file, but it should be easy to reproduce. Just write some gibberish like
```
def  aaa(list  :   intz ,   bbbbbb)  :
    1   + "a"
```
and duplicate it until you have 500 warnings or so. You can also `(setq flymake-collection-ruff-args '("--select=ALL"))` to get some more warnings. Now when typing, Flymake will be blocking user input while it is waiting for the flymake-collection-ruff backend.

I am using a recent snapshot of emacs built with the new json parser and native compilation.

**Comment by mohkale** [comment]
I can think of a few possible reasons for this. A basic profiler just shows flymake is slow to render all the lints, but it could be because the command produces a lot of output which we parse into a string and then json or because the command is bufferring weirdly. I'll take a closer look when I get a chance.

**Comment by fbergroth** [comment]
Right, it would be nice to find the culprit. It could be something specific to flymake-collection since `python-flymake` backend runs smoothly with
```
(setq python-flymake-command '("ruff" "--quiet" "check" "--preview" "--output-format=pylint" "--stdin-filename=stdin" "-"))
```
A small difference is that ruff will only output line numbers and not columns with that, so perhaps fewer overlays are created.

**Comment by fbergroth** [comment]
When python-flymake is configured to to match both line and columns from ruff output, it stutters just as bad. So probably there's no issue in flymake-collection.

Edit: it was actually caused by slowness in `python-nav-forward-sexp` (called via `flymake-diag-region`). If I `(setq forward-sexp-function nil)` in the python buffer, it's all smooth. :dizzy_face:

**Comment by mohkale** [comment]
That's good to hear. Could you upstream a bug ticket to the Emacs mailing list letting them know? Either forward-sexp-function needs to be blanked in flymake or the python ones performance needs to be improved.
