### ISSUE TITLE
flymake-collection-jq reports ok for invalid json

### ISSUE THREAD

**Issue by uqix** [mohkale/flymake-rest#33]
While `flymake-collection-jsonlint` works as expected.

* jq version: 1.7.1
* flymake-collection version: 20231226.1614
* jsonlint version: 1.6.0

**Comment by mohkale** [comment]
Could you share the invalid json in question? Can't really confirm without that :sweat_smile:.

**Comment by uqix** [comment]
e.g. 
```json
{
  "a": 1,
  "b": "...",
  ""
}

```

**Comment by mohkale** [comment]
Seems like jq changed the output to include a jq: prefix at some point. Should be fixed now.
