### ISSUE TITLE
`elisp-mode` reference

### ISSUE THREAD

**Issue by gs-101** [mohkale/flymake-rest#44]
`elisp-mode` is referenced as [one of the first](https://github.com/mohkale/flymake-collection/blob/630caa55d7c64a30c9063e229b7af1070781f957/src/flymake-collection-hook.el#L42) modes in `flymake-collection-hook-config`. Is this variable correct?

This is also mentioned in #38.

**Comment by mohkale** [comment]
I think you're right. This should be fixed with #38 being merged.
