### ISSUE TITLE
Package for GNU Guix

### ISSUE THREAD

**Issue by jgarte** [mohkale/flymake-rest#8]
Hi, I'd like to package this for GNU Guix but I'm not sure what commit I should use:

https://issues.guix.gnu.org/57667

Any suggestions?

**Comment by mohkale** [comment]
@jgarte 

> I'd like to package this for GNU Guix but I'm not sure what commit I should use

Hello. I'd recommend a tag over a commit if that would be possible. I've just pushed a new tag to the release branch of this repo. Please use that. If not then the commit referenced by the tag should also work.

**Comment by jgarte** [comment]
The Guix package for `flymake-collection` at `v1.0.1` has been merged in upstream.

https://issues.guix.gnu.org/57667#5

@mohkale 

Is it too soon to make a new release after #9 got merged?
